version: "3.9"

services:
  db:
    image: docker.io/bitnami/postgresql:11
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=gtubt
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres

volumes:
  postgresql_data:
    driver: local
