version: "3.9"

services:
    web:
        build: .
        ports:
            - "3000:3000"
        volumes:
            - ./app:/usr/src/app/app
            - ./gtubt_db_dev:/usr/src/app/gtubt_db_dev