# Generated by Django 3.2.5 on 2021-08-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210829_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_accept_kvkk',
            field=models.BooleanField(default=False, verbose_name='KVKK'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_accept_user_agreement',
            field=models.BooleanField(default=False, verbose_name='User Agreement'),
        ),
    ]
